name: Trigger auto deployment for runner-functions-nightly60

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/runner-functions-nightly60-AutoDeployTrigger-9dea240d-d5a9-40d9-bc8d-554d671bbffa.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.RUNNERFUNCTIONSNIGHTLY60_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUNNERFUNCTIONSNIGHTLY60_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUNNERFUNCTIONSNIGHTLY60_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: swiftfiddle.azurecr.io
          registryUsername: ${{ secrets.RUNNERFUNCTIONSNIGHTLY60_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUNNERFUNCTIONSNIGHTLY60_REGISTRY_PASSWORD }}
          containerAppName: runner-functions-nightly60
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle.azurecr.io/runner-functions-nightly60:latest
          _buildArgumentsKey_: |
            _buildArgumentsValues_
